# Generated by Django 4.0.3 on 2022-04-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_login_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='country',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
