# Generated by Django 4.0.3 on 2022-04-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_login_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='image',
            field=models.ImageField(default=0, upload_to='Login'),
            preserve_default=False,
        ),
    ]
